[workspace]
authors = ["A283le <alexdominguez169@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mov-detection"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025060513,<26"
